"""message schema foundation

Revision ID: 89507b65cda7
Revises: 
Create Date: 2026-07-18 12:41:55.912364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89507b65cda7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    'messages',
    sa.Column(
        'is_read',
        sa.Boolean(),
        nullable=False,
        server_default=sa.false()
    )
)
    op.add_column('messages', sa.Column('read_at', sa.DateTime(), nullable=True))
    op.add_column('messages', sa.Column('edited_at', sa.DateTime(), nullable=True))
    op.add_column(
    'messages',
    sa.Column(
        'is_deleted',
        sa.Boolean(),
        nullable=False,
        server_default=sa.false()
    )
)
    op.add_column('messages', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('messages', sa.Column('reply_to_message_id', sa.Integer(), nullable=True))
    # op.create_foreign_key(None, 'messages', 'messages', ['reply_to_message_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_column('messages', 'reply_to_message_id')
    op.drop_column('messages', 'deleted_at')
    op.drop_column('messages', 'is_deleted')
    op.drop_column('messages', 'edited_at')
    op.drop_column('messages', 'read_at')
    op.drop_column('messages', 'is_read')
    # ### end Alembic commands ###
